# Generated by Django 5.1.4 on 2025-01-21 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialSound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to=settings.AUTH_USER_MODEL),
        ),
    ]
